
import javax.swing.JOptionPane;


public class StudentGade extends javax.swing.JFrame {

    
    
    public StudentGade() {
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allItems = new javax.swing.JPanel();
        s_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        Grade = new javax.swing.JTextField();
        Physics = new javax.swing.JTextField();
        English = new javax.swing.JTextField();
        Section = new javax.swing.JTextField();
        Chemistry = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TotalMarks = new javax.swing.JTextField();
        Percentage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        CalcualteBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        Maths = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allItems.setBackground(new java.awt.Color(250, 198, 198));
        allItems.setForeground(new java.awt.Color(153, 153, 153));

        s_ID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_IDActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Student Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Student ID");

        studentName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });

        Grade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeActionPerformed(evt);
            }
        });

        Physics.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Physics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysicsActionPerformed(evt);
            }
        });

        English.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        English.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishActionPerformed(evt);
            }
        });

        Section.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionActionPerformed(evt);
            }
        });

        Chemistry.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Chemistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemistryActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Enter Chemistry mark");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Enter Physics mark");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Enter Maths mark");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Khalid Al Hadi School");

        TotalMarks.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalMarksActionPerformed(evt);
            }
        });

        Percentage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Enter English mark");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Percentage");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Total Marks");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Grade");

        ExitBtn.setBackground(new java.awt.Color(255, 51, 51));
        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        CalcualteBtn.setBackground(new java.awt.Color(0, 204, 102));
        CalcualteBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CalcualteBtn.setForeground(new java.awt.Color(255, 255, 255));
        CalcualteBtn.setText("Calculate");
        CalcualteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcualteBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(51, 51, 255));
        ClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        Maths.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Section");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("The Result (⓿_⓿)");

        javax.swing.GroupLayout allItemsLayout = new javax.swing.GroupLayout(allItems);
        allItems.setLayout(allItemsLayout);
        allItemsLayout.setHorizontalGroup(
            allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allItemsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(allItemsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allItemsLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(allItemsLayout.createSequentialGroup()
                        .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CalcualteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(allItemsLayout.createSequentialGroup()
                        .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(allItemsLayout.createSequentialGroup()
                                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(s_ID)
                                        .addComponent(jLabel8)
                                        .addComponent(Physics, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Maths, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Chemistry, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(English)
                                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(allItemsLayout.createSequentialGroup()
                                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(Grade)
                                    .addComponent(jLabel12)
                                    .addComponent(TotalMarks)
                                    .addComponent(jLabel13)
                                    .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        allItemsLayout.setVerticalGroup(
            allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allItemsLayout.createSequentialGroup()
                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(allItemsLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel9)
                        .addGap(123, 123, 123))
                    .addGroup(allItemsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(allItemsLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(s_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(Physics, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel8)
                                    .addGap(27, 27, 27)
                                    .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Chemistry, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Maths, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(allItemsLayout.createSequentialGroup()
                                    .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(allItemsLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(English, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(allItemsLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(129, 129, 129)))
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel6)))
                            .addGroup(allItemsLayout.createSequentialGroup()
                                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(allItemsLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(allItemsLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TotalMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129)))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Grade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(allItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcualteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(allItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PercentageActionPerformed

    private void TotalMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalMarksActionPerformed

    private void ChemistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemistryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChemistryActionPerformed

    private void SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionActionPerformed

    private void EnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishActionPerformed

    private void PhysicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhysicsActionPerformed

    private void GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeActionPerformed

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void s_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_IDActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void CalcualteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcualteBtnActionPerformed

//      take the name   
        String s_name = studentName.getText();
        String s_sec = Section.getText();
        String s_id = s_ID.getText();
        
//      convernt string to double   
        double py = Double.parseDouble(Physics.getText());
        double che = Double.parseDouble(Chemistry.getText());
        double math = Double.parseDouble(Maths.getText());
        double en = Double.parseDouble(English.getText());
        
//      calc the total   
        double total = py + che + math + en;
//      display total  
        TotalMarks.setText(""+total);
//      calc
        double per = (py + che + math + en) / 4;
        Percentage.setText(""+per);
        
        String grade = null;
        // Grade calculation 
        if (per > 90) { 
            grade = "A "; 
        } else if ((per > 85) && (per < 90)) { 
            grade = "B "; 
        } else if ((per > 80) && (per < 85)) { 
            grade = "C "; 
        } else if ((per > 70) && (per < 80)) { 
            grade = "D "; 
        } else if ((per > 60) && (per < 70)) { 
            grade = "E "; 
        } else if ((per > 50) && (per < 60)) { 
            grade = "Poor ";
        } else {
            grade = "Enter Your grade";
        }
        
        Grade.setText(""+grade);
        
        JOptionPane.showMessageDialog(null, "Welcom to Khalid School 🌹 \n"
                + "Hello: " + s_name + " With ID " +s_id+ " of class: " + s_sec + 
                "\nYour Grade is: " + grade
        );
    }//GEN-LAST:event_CalcualteBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed

        
        Physics.setText(""); 
        Chemistry.setText(""); 
        Section.setText(""); 
        English.setText(""); 
        s_ID.setText(""); 
        studentName.setText(""); 
        TotalMarks.setText(""); 
        Percentage.setText(""); 
        Grade.setText("");
        Section.setText("");
        
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void MathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MathsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcualteBtn;
    private javax.swing.JTextField Chemistry;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField English;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JTextField Grade;
    private javax.swing.JTextField Maths;
    private javax.swing.JTextField Percentage;
    private javax.swing.JTextField Physics;
    private javax.swing.JTextField Section;
    private javax.swing.JTextField TotalMarks;
    private javax.swing.JPanel allItems;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField s_ID;
    private javax.swing.JTextField studentName;
    // End of variables declaration//GEN-END:variables

}

